from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from app.model_service import model_service
from app.schemas import PredictionResponse


app = FastAPI(
    title="Skin XAI API",
    description="FastAPI backend for skin disease classification and Grad-CAM heatmap generation.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


SAFETY_WARNING = (
    "This result is generated by an experimental AI model. "
    "It is not a medical diagnosis. Please consult a qualified healthcare "
    "professional for medical concerns."
)


@app.get("/")
def root():
    return {
        "message": "Skin XAI API is running.",
        "status": "ok",
    }


@app.get("/health")
def health():
    return {
        "status": "healthy",
        "model_loaded": True,
        "num_classes": model_service.num_classes,
        "image_size": model_service.image_size,
    }


@app.get("/classes")
def get_classes():
    return {
        "idx_to_class": model_service.idx_to_class,
        "class_to_idx": model_service.class_to_idx,
    }


@app.post("/predict", response_model=PredictionResponse)
async def predict(file: UploadFile = File(...)):
    if file.content_type not in ["image/jpeg", "image/png", "image/webp"]:
        raise HTTPException(
            status_code=400,
            detail="Unsupported file type. Please upload JPEG, PNG, or WEBP image.",
        )

    image_bytes = await file.read()

    if len(image_bytes) == 0:
        raise HTTPException(
            status_code=400,
            detail="Empty image file.",
        )

    try:
        result = model_service.predict_with_gradcam(image_bytes)

        return PredictionResponse(
            predicted_class_id=result["predicted_class_id"],
            predicted_class=result["predicted_class"],
            confidence=result["confidence"],
            top_k=result["top_k"],
            heatmap_base64=result["heatmap_base64"],
            warning=SAFETY_WARNING,
        )

    except Exception as error:
        raise HTTPException(
            status_code=500,
            detail=f"Prediction failed: {str(error)}",
        )